# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 524c3cdfef4a6f801f8217ca471712c877062d604d9b78eb37d3a1a3b7be31742ea8941bcccc1c854d6acb6365ec5cb6675adb2327c7a9386b91864eb5d51969

test:
  secret_key_base: 443bc86785e4809e2504b6487036360d62130c453f26028eadfd80b624619c4afd70a3c2d684d8df364af8c15ac2f61d415042396e01ab487b419ca240cd0a2c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
